name: Run Gist

on:
  schedule:
    - cron: '50 16 * * *'
    - cron: '50 21 * * *'
    - cron: '50 3 * * *'
    - cron: '50 9 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python gist.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if git status --porcelain | grep -q 'gist.txt'; then
            git add gist.txt
            git commit -m "chore: Update gist.txt URLs"
            git push
          else
            echo "No changes to commit. Skipping commit step."
          fi
